### ISSUE TITLE
Classify: screen doesn't rearrange correctly when rotated

### ISSUE THREAD

**Issue by vrooje** [murraycu/ios-galaxyzoo#10]
I'm using the app with my iPad; I've noticed that if I rotate my screen during the classification the new placement of the items on the screen is a little weird, such that often some of the answer choices end up off the screen. If I answer the question while rotated, the next question comes up with the correct alignment.

![img_0024](https://cloud.githubusercontent.com/assets/2357126/9424287/c13189e8-48de-11e5-8b4e-6a929f0ca0a1.PNG)
![img_0025](https://cloud.githubusercontent.com/assets/2357126/9424288/c131eb5e-48de-11e5-922b-bbaf9557dae6.PNG)

**Comment by murraycu** [comment]
Yes, rotation needs lots of attention.

For the iPhone, I might just disable rotation. I don't see how it can ever be arranged usefully in landscape on an iPhone.

**Comment by vrooje** [comment]
Agreed!

**Comment by murraycu** [comment]
The problem with the button sizes and positions is fixed by commit 1b1ffe8fa8cfc1ffa251f03eae309e69d2c9ae98 .

I've opened this issue about the general landscape layout on iPad:
https://github.com/murraycu/ios-galaxyzoo/issues/12
(Incidentally, there doesn't seem to be any way to stop the app being installed on iPad in the meantime.)
